import os
import time
import logging
import subprocess
import papermill
from icepop.enrichment_analysis import EnrichmentPipeline
from importlib.resources import files

logger = logging.getLogger("icepop.interactive")


def interactive(
    outdir: str,
    geneset_collections: str,
    geneset_path: str = None,
    adata_path: str = None
):
    """
    Run enrichment analysis and generate an interactive report.

    This function performs gene set enrichment analysis using the
    specified collections or a custom gene set file, and then executes
    a Jupyter notebook to produce a summarized HTML report.

    Parameters
    ----------
    outdir : str
        Output directory where enrichment results and reports will be saved.

    geneset_collections : str
        Name of predefined gene set collections to use. Use "none" if
        providing a custom gene set file via ``geneset_path``.


    geneset_path : str, optional
        Path to a custom gene set file. Required if
        ``geneset_collections`` is set to "none".

    adata_path : str, optional
        Path to an AnnData (.h5ad) file passed to the notebook for
        downstream visualization and analysis.

    Raises
    ------
    ValueError
        If required arguments are missing or inconsistent.

    RuntimeError
        If enrichment analysis or notebook execution fails.

    Notes
    -----
    The report is generated by executing the notebook using ``papermill``
    and converting it to HTML via ``jupyter nbconvert``.
    """

    if not outdir:
        raise ValueError("outdir is required")

    if geneset_collections.lower() == "none" and not geneset_path:
        raise ValueError("--geneset_path required when geneset_collections=None")

    if geneset_path and not os.path.exists(geneset_path):
        raise FileNotFoundError(f"geneset_path not found: {geneset_path}")

    os.makedirs(outdir, exist_ok=True)
    logger.info(f"Enrichment output directory: {outdir}")
    logger.info("Starting enrichment analysis...")
    start = time.perf_counter()
    try:
        pipeline = EnrichmentPipeline(
            outdir=outdir,
            geneset_collections=geneset_collections,
            geneset_path=geneset_path,)
        pipeline.run()
    except Exception as e:
        logger.error(f"Enrichment analysis failed: {e}")
        raise

    elapsed = time.perf_counter() - start
    notebook = files("icepop").joinpath("templates/ICEPOP-SUMMARY.ipynb")
    logger.info(f"Enrichment completed in {elapsed:.2f} seconds")
    logger.info("Generating summary report...")
    try:
        executed_nb = os.path.join(outdir, "icepop-report.ipynb")
        subprocess.run([
            "/mnt/ufs18/rs/FishEvoDevoGeno/Hao/icepop_analysis/.venv/bin/papermill",
            notebook,
            executed_nb,
            "-p", "outdir", outdir,
            "-p", "adata_path", adata_path], check=True)
        subprocess.run([
            "jupyter", "nbconvert",
            "--to", "html",
            executed_nb,
            "--output-dir", outdir], check=True)
    except subprocess.CalledProcessError as e:
        logger.error(f"Error running notebook: {e}")
        raise

    logger.info(f"Notebook executed and saved to {outdir}")
