from pathlib import Path
import scanpy as sc
import pandas as pd
from MetaQ_sc import run_metaq
import logging

logger = logging.getLogger("icepop.metacell")


def metacell(
    h5ad: str,
    outdir: str,
    ncell_per_mc: int = 75,
    save_name: str = 'metaq_res',
    ct_key: str = 'cell_type',
    device: str = 'cuda',
):
    """
    Construct metacells from single-cell RNA-seq data using MetaQ.

    This command groups single cells into metacells with similar expression
    profiles, producing a reduced representation that is robust to noise and
    suitable for downstream association and influence analyses in ICePop.

    Parameters
    ----------
    h5ad : str
        Path to input AnnData (.h5ad) file containing single-cell expression data.
    outdir : str
        Output directory where MetaQ results will be written.
    ncell_per_mc : int, default=75
        Target number of cells per metacell. The total number of metacells is
        determined as approximately n_cells / ncell_per_mc.
    save_name : str, default='metaq_res'
        Prefix for output files generated by MetaQ.
    ct_key : str, default='cell_type'
        Column name in `adata.obs` specifying cell-type annotations.
        Used to evaluate metacell purity.
    device : str, default='cuda'
        Compute device to use. Options include 'cuda' or 'cpu'.

    Outputs
    -------
    - Metacell assignment file (CSV)
    - MetaQ intermediate and result files saved under `outdir`

    Notes
    -----
    - Input expression matrix must contain raw (unnormalized) counts.
    - Metacells are constructed independently of downstream association tests.
    """

    adata = sc.read_h5ad(h5ad)

    # mkdir
    Path(outdir).mkdir(exist_ok=True)

    # check ct key
    if ct_key not in adata.obs:
        raise KeyError(f"Cell-type key '{ct_key}' not found in adata.obs")

    # check count/log normed
    max_val = adata.X.max()
    logger.info(f"Max expression value: {max_val}")

    if max_val <= 15:
        logger.warning(
            "Max expression value (%s) is low; verify that input is raw counts.",
            max_val,
        )

    # check stats
    tot_n_cell = adata.shape[0]
    target_num = int(round(tot_n_cell / ncell_per_mc))
    logger.info(f'Totol number of cells: {tot_n_cell}, target metacell number: {target_num}')

    # metacell id file
    metacellids_h5ad = f'./save/{save_name}_{target_num}metacell_ids.h5ad'

    # run metaq
    if not Path(metacellids_h5ad).exists():
        logger.info("Running MetaQ")
        try:
            run_metaq(
                data_path=[
                    h5ad,
                ],  # the path to the input h5ad data
                data_type=[
                    "RNA",
                ],  # the type of the input data
                metacell_num=target_num,  # the target number of metacells
                save_name=save_name,  # the file name prefix when saving the results
                type_key=ct_key,
                device=device
            )
        except KeyError as e:
            logger.warning(
                f"[INFO] MetaQ evaluation failed (celltype mapping), ignored: {e}"
            )

    # save metacell assignment
    metacellid_adata = sc.read(metacellids_h5ad)
    with open(f'{outdir}/mc_assign.csv', 'w') as f:
        for i in metacellid_adata.obs['metacell']:
            f.write(f'metacell-{i}\n')

    # purity stats
    adata.obs['metacell'] = [f'metacell-{i}' for i in metacellid_adata.obs['metacell']]
    freq_df = pd.crosstab(adata.obs[ct_key], adata.obs['metacell'])
    freq_df = freq_df.div(freq_df.sum(0))

    # get metacell size and ct size
    mc_cnt = adata.obs['metacell'].value_counts()
    ct_cnt = adata.obs['cell_type'].value_counts()

    mc2ct_df = pd.DataFrame({
        "cell_type": freq_df.idxmax(axis=0),
        "purity": freq_df.max(axis=0),
    })
    mc2ct_df['metacell_size'] = mc_cnt.loc[mc2ct_df.index].values
    mc2ct_df['cell_type_size'] = ct_cnt.loc[mc2ct_df['cell_type']].values
    mc2ct_df.to_csv(f'{outdir}/mc_stats.csv', header=True, index=True)

    # print stats
    logger.info("Overall purity stats:\n%s", mc2ct_df["purity"].describe())
